-- CreateEnum
CREATE TYPE "PayoutType" AS ENUM ('WITHDRAWAL', 'AIRTIME', 'DATA', 'ELECTRICITY', 'CABLETV');

-- AlterTable
ALTER TABLE "payouts" ADD COLUMN     "type" "PayoutType" NOT NULL DEFAULT 'WITHDRAWAL',
ALTER COLUMN "bankAccount" DROP NOT NULL,
ALTER COLUMN "bankCode" DROP NOT NULL,
ALTER COLUMN "bankName" DROP NOT NULL;
